"""create scheduled emails table

Revision ID: af5b38d455c5
Revises: 50cf19e202bb
Create Date: 2026-08-26 21:17:41.020494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af5b38d455c5'
down_revision: Union[str, Sequence[str], None] = '50cf19e202bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['email_senders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_emails_idempotency_key'), 'scheduled_emails', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_scheduled_emails_scheduled_at'), 'scheduled_emails', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_scheduled_emails_sender_id'), 'scheduled_emails', ['sender_id'], unique=False)
    op.create_index(op.f('ix_scheduled_emails_status'), 'scheduled_emails', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_emails_status'), table_name='scheduled_emails')
    op.drop_index(op.f('ix_scheduled_emails_sender_id'), table_name='scheduled_emails')
    op.drop_index(op.f('ix_scheduled_emails_scheduled_at'), table_name='scheduled_emails')
    op.drop_index(op.f('ix_scheduled_emails_idempotency_key'), table_name='scheduled_emails')
    op.drop_table('scheduled_emails')
    # ### end Alembic commands ###
