"""add processing started timestamp

Revision ID: c274548078a1
Revises: f6ee72a010d2
Create Date: 2026-08-28 14:10:06.202956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c274548078a1'
down_revision: Union[str, Sequence[str], None] = 'f6ee72a010d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_emails', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_emails', 'processing_started_at')
    # ### end Alembic commands ###
