"""create email recipients table

Revision ID: f6ee72a010d2
Revises: af5b38d455c5
Create Date: 2026-08-26 21:31:13.149273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ee72a010d2'
down_revision: Union[str, Sequence[str], None] = 'af5b38d455c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_recipients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scheduled_email_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scheduled_email_id'], ['scheduled_emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_recipients_email'), 'email_recipients', ['email'], unique=False)
    op.create_index(op.f('ix_email_recipients_scheduled_email_id'), 'email_recipients', ['scheduled_email_id'], unique=False)
    op.create_index(op.f('ix_email_recipients_status'), 'email_recipients', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_recipients_status'), table_name='email_recipients')
    op.drop_index(op.f('ix_email_recipients_scheduled_email_id'), table_name='email_recipients')
    op.drop_index(op.f('ix_email_recipients_email'), table_name='email_recipients')
    op.drop_table('email_recipients')
    # ### end Alembic commands ###
